#ifndef GENO_ITEMS_H
#define GENO_ITEMS_H
#include "geno.h"
#define GENO_ITEM_KIND_BASE GENO_ART_KIND_END
#define GENO_ITEM_MAX_DEFS 64
#define GENO_ITEM_KIND_END (GENO_ITEM_KIND_BASE + GENO_ITEM_MAX_DEFS)
/* Scalar-only game/native contract; float fields use IEEE float bit patterns. */
int Geno_ItemActive(int kind);
enum GenoItemParam {
 GENO_IP_DEFINED, GENO_IP_GRAVITY, GENO_IP_TERMINAL, GENO_IP_BOUNCE,
 GENO_IP_FRICTION, GENO_IP_FLOOR_REST, GENO_IP_STAGE_COLLISION,
 GENO_IP_LIFETIME, GENO_IP_BLINK, GENO_IP_COLLECT, GENO_IP_RADIUS,
 GENO_IP_PORT_MASK, GENO_IP_TEAM_MASK, GENO_IP_SCALE, GENO_IP_SPIN,
 GENO_IP_BOB, GENO_IP_BOB_SPEED, GENO_IP_CAP,
 GENO_IP_HOVER, GENO_IP_TILT, GENO_IP_HEIGHT, GENO_IP_COUNT
};
enum GenoItemRead { GENO_II_HANDLE, GENO_II_DEF, GENO_II_OWNER,
 GENO_II_COLOUR, GENO_II_AMOUNT, GENO_II_AGE, GENO_II_KIND,
 GENO_II_VISIBLE, GENO_II_COUNT };
enum GenoItemFloat { GENO_IF_X, GENO_IF_Y, GENO_IF_VX, GENO_IF_VY,
 GENO_IF_Z, GENO_IF_COUNT };
enum GenoItemVisual { GENO_IV_Y, GENO_IV_ROT_Y, GENO_IV_SCALE, GENO_IV_TILT };
#endif
