"""Regenerate gw_script_comm.inc (the gd.comm Lua as C string literals) from gw_comm.lua."""
from pathlib import Path

here = Path(__file__).resolve().parent
BS = chr(92)
src = (here / "gw_comm.lua").read_text(encoding="utf-8").replace("\r\n", "\n")
out = ["/* Generated by gen_comm_inc.py from gw_comm.lua; do not edit. */", "static const char gs_comm_lua[] ="]
for line in src.rstrip("\n").split("\n"):
    esc = line.replace(BS, BS + BS).replace('"', BS + '"')
    out.append('    "' + esc + BS + 'n"')
out[-1] += ";"
(here / "gw_script_comm.inc").write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
