/* gw_mex_bridge.h - guest->native bridge table for the PPC blob interpreter.
 *
 * GENERATED by tools/mex_port/gen_bridge.py - do not edit by hand. Pairs symbols.txt guest
 * addresses with melee-pc.map gw_ native VAs, so the interpreter resolves absolute guest
 * addresses (bl/bctrl targets and static globals) to the port's native `gw_` code/data.
 */
#ifndef GW_MEX_BRIDGE_H
#define GW_MEX_BRIDGE_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Look up a guest address. Returns the native VA, or 0 when there is no bridge entry. `kind`
 * is set to 1 for a function, 0 for a data object (may be NULL). */
uint32_t gw_mex_bridge_lookup(uint32_t guest_addr, int *kind);

/* Number of entries (for tests/diagnostics). */
uint32_t gw_mex_bridge_count(void);

#ifdef __cplusplus
}
#endif
#endif /* GW_MEX_BRIDGE_H */
