/* generated by menu/pipeline/atlas_tokens.py from the Atlas tokens.css: do not edit */
#ifndef GW_UI_TOKENS_H
#define GW_UI_TOKENS_H

#define AT_C_GROUND 0x0D1015FFu
#define AT_C_GROUND2 0x131820FFu
#define AT_C_PLATE 0x1A1F29FFu
#define AT_C_PLATE2 0x222836FFu
#define AT_C_LIFT 0x2E3648FFu
#define AT_C_EDGE 0x06080BFFu
#define AT_C_EDGE2 0x0B0E13FFu
#define AT_C_LINE 0x323A4BFFu
#define AT_C_LINE2 0x4A5570FFu
#define AT_C_SCRIM 0x05070AB8u
#define AT_C_IVORY 0xF1EBDCFFu
#define AT_C_TEXT2 0xC8C4B8FFu
#define AT_C_MUTED 0x9AA2B4FFu
#define AT_C_DIM 0x6E768AFFu
#define AT_C_INK 0x0B0D12FFu
#define AT_C_EMBER 0xFF7A3DFFu
#define AT_C_EMBER_D 0xA8431CFFu
#define AT_C_JADE 0x4FD6AAFFu
#define AT_C_JADE_D 0x1F6E57FFu
#define AT_C_SUN 0xF2C14EFFu
#define AT_C_ROSE 0xEF4F7DFFu
#define AT_C_P1 0xF0504AFFu
#define AT_C_P2 0x4A90FFFFu
#define AT_C_P3 0xF3CF3EFFu
#define AT_C_P4 0x42D68BFFu
#define AT_C_CPU 0x8F98AAFFu
#define AT_C_PAD_A 0x3DBB78FFu
#define AT_C_PAD_B 0xE5534BFFu
#define AT_C_PAD_X 0x9AA3B5FFu
#define AT_C_PAD_Z 0x8E6BDCFFu

#define AT_PX_T_CAP 12
#define AT_PX_T_BODY 14
#define AT_PX_T_ROW 16
#define AT_PX_T_LABEL 20
#define AT_PX_T_TITLE 28
#define AT_PX_T_HERO 44
#define AT_PX_T_DISPLAY 64
#define AT_PX_S1 4
#define AT_PX_S2 8
#define AT_PX_S3 12
#define AT_PX_S4 16
#define AT_PX_S5 24
#define AT_PX_CH 8
#define AT_PX_CH_S 5
#define AT_PX_CH_XS 3

#define AT_MS_FOCUS 80
#define AT_MS_TAB 120
#define AT_MS_PANE 100
#define AT_MS_MODAL 140
#define AT_MS_NOTE 160
#define AT_MS_TURN 12000

#endif
