-- @name: area-streaming
-- @gameplay: true
-- @rollback_safe: false
-- Native fixture: mode=lab;p1=fox;p2=none;stage=bf;time=0
-- Uses original scalar geometry only; no external model/disc-derived fixture.
gd.run(function()
    local ok, why = pcall(function()
        assert(gd.wait_until(function() return gd.match().active and gd.match().frame > 90 end, 3000))
        gd.history(0)
        local before = gd.stage_stats()
        local handle = gd.area_prepare('fixture-room', function()
            for i = 0, 17 do assert(gd.stage_add_line(4000+i*10, 500, 4010+i*10, 500, 'floor')) end
        end)
        assert(handle and gd.area_status(handle) == 'prepared')
        assert(not gd.area_loaded('fixture-room'))
        assert(gd.floor_below(4005, 520, 40) == nil, 'prepared collision must be absent')
        assert(gd.area_prepare('fixture-room') == handle)
        gd.savestate(5)
        assert(gd.area_activate(handle) and gd.area_status(handle) == 'active')
        assert(gd.floor_below(4005, 520, 40), 'activation exposes prepared floor')
        assert(not gd.area_load('fixture-room', function() error('duplicate builder') end))
        assert(gd.area_unload('fixture-room') and gd.area_status(handle) == 'unloading')
        assert(gd.floor_below(4005, 520, 40) == nil, 'unload hides collision immediately')
        assert(gd.stage_stats().lines == before.lines, 'logical stats exclude retired lines')
        assert(gd.wait_until(function() return gd.area_status(handle) == 'missing' end, 64), 'bounded deferred drain')
        gd.loadstate(5)
        gd.wait(3)
        assert(gd.area_status(handle) == 'prepared' and not gd.area_loaded('fixture-room'))
        assert(gd.floor_below(4005, 520, 40) == nil)
        assert(gd.area_activate(handle))
        gd.history(180)
        gd.wait(120)
        assert(gd.rewind_test(60, true), 'prepared activation state survives exact replay')
        gd.area_unload('fixture-room')
        gd.wait(30)
    end)
    gd.log('TEST area-streaming '..(ok and 'PASS' or ('FAIL '..tostring(why))))
    gd.quit()
end)
