/* atlas-settings: every settings page, from the REAL tables' shapes (pc/tests/atlas_settings_tables.inc, generated by tools/port/settings_descriptors.py), through the real table
 * walker and the real settings host (gw_script_ui_set.inc), drawn at 640 and 853 with the style checks. The getters and setters are stand-ins; the real ones are proved in the game. */
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <windows.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
#include "gw_kit.h"
#include "gw_screen_model.h"
#include "atlas_check.h"
#include "atlas_fake.h"
#include "atlas_rec.h"

typedef struct { char id[64]; int used, disabled, gameplay; } GsScript;
static struct { lua_State *L; int cur, console, n, scene_kind, match_active; GsScript s[8]; unsigned char key_now[256]; } gs;
static int g_may_run = 1, g_quads, g_art_calls, g_art_ret = 5;
static double g_now = 1000.0;
static float g_track;
static unsigned g_pad;
static char g_last[512];
static char g_art_key[64];

void gw_log(const char *fmt, ...) { (void) fmt; }
static int gs_may_run(int i) { (void) i; return g_may_run; }
int gw_RB_Enabled(void) { return 0; }
static int gs_ui_port_read(int port, char *name, int cap, int *percent, int *stocks, int *cpu)   /* the fighter readbacks gd.player uses */
{
    (void) port; (void) cap; name[0] = 0; *percent = *stocks = *cpu = 0;
    return 0;
}
int gw_Netplay_Enabled(void) { return 0; }
int gw_Mods_Count(void) { return 0; }
int gw_Mods_MenuCount(int i) { (void) i; return 0; }
const char *gw_Mods_MenuField(int i, int k, const char *f) { (void) i; (void) k; (void) f; return ""; }
const char *gw_Mods_Id(int i) { (void) i; return ""; }
static int gs_pcall(int script, int nargs, int nres, const char *what)
{
    int old = gs.cur, rc = 0;
    (void) what;
    gs.cur = script;
    if (lua_pcall(gs.L, nargs, nres, 0) != LUA_OK) { lua_pop(gs.L, 1); rc = -1; }
    gs.cur = old;
    return rc;
}
static int gs_get_hook(int i, const char *name)
{
    if (!gs.s[i].used || gs.s[i].disabled) return 0;
    lua_getglobal(gs.L, name);
    if (lua_isfunction(gs.L, -1)) return 1;
    lua_pop(gs.L, 1);
    return 0;
}
static const GsScript *gs_cur_script(void) { return &gs.s[gs.cur]; }
static double gs_now_ms(void) { return g_now; }
static double gs_ui_clock;
static struct { int token; } gs_stage_models[4];
static int gs_stage_nmodels;
int gw_ScriptGame_ModelRefOwned(int a, int b, int c, int d) { (void) a; (void) b; (void) c; (void) d; return 0; }
int gw_Script_StageResourceOwner(void) { return 0; }
static int gs_sm_emit(int asset, const GsmParams *p, int clip, const char **why) { (void) asset; (void) p; (void) clip; (void) why; return 0; }
void gw_script_pad_state(int ch, unsigned *b, int *sx, int *sy, int *cx, int *cy, int *tl, int *tr) { (void) ch; *b = 0; *sx = *sy = *cx = *cy = *tl = *tr = 0; }
unsigned gw_script_pad_raw_buttons(int ch) { (void) ch; return g_pad; }
static float g_mx = -1000.0f, g_my = -1000.0f, g_mwheel; static int g_mbuttons;
void gw_Mouse_ScriptRead(float *x, float *y, int *buttons, float *wheel) { *x = g_mx; *y = g_my; *buttons = g_mbuttons; *wheel = g_mwheel; }
float gw_Console_ScriptWidth(void) { return 640.0f; }
int gw_Settings_Int(const char *k, int d) { (void) k; return d; }
static void gs_prof_setfuncs(lua_State *L, const luaL_Reg *funcs, const char *prefix) { (void) prefix; luaL_setfuncs(L, funcs, 0); }
static int gs_kit_record(int first, int added) { (void) first; return added; }
static double gs_kit_optnum(lua_State *L, int t, const char *k, double def)
{
    double v = def;
    if (!lua_istable(L, t)) return def;
    lua_getfield(L, t, k);
    if (lua_isnumber(L, -1)) v = lua_tonumber(L, -1);
    lua_pop(L, 1);
    return v;
}
int gw_Kit_Available(void) { return 1; }
const char *gw_Kit_Why(void) { return ""; }
const char *gw_Kit_RoleMissingPage(int role) { (void) role; return NULL; }
int gw_Kit_Role(const char *name) { return name != NULL && name[0] == 'a' && name[1] == '_' ? 3 : -1; }
float gw_Kit_TextWidth(int role, const char *s) { (void) role; return 6.0f * (float) strlen(s) + g_track * (float) strlen(s); }
int gw_Kit_DrawText(float x, float y, const char *s, int role, uint32_t rgba, int align, float max_w, float shear, float *out_w)
{ (void) x; (void) y; (void) role; (void) rgba; (void) align; (void) max_w; (void) shear; if (out_w) *out_w = 0.0f; g_quads += (int) strlen(s); return (int) strlen(s); }
int gw_Kit_DrawPoly4(const float x[4], const float y[4], uint32_t rgba) { (void) x; (void) y; (void) rgba; g_quads++; return 1; }
static int g_images;
int gw_Kit_DrawImage(int tex, float x, float y, float w, float h, uint32_t rgba, int flip, float shear) { (void) tex; (void) x; (void) y; (void) w; (void) h; (void) rgba; (void) flip; (void) shear; g_quads++; g_images++; return 1; }
void gw_Kit_SetTracking(float px) { g_track = px; }
static int g_hsd_frame; void gw_Kit_TexHsdFrame(int frame) { g_hsd_frame = frame; }
static int g_hsd_drops; void gw_Kit_TexDropHsd(void) { g_hsd_drops++; }
int gw_Kit_TexAddHsd(const char *key, int gx_fmt, const uint8_t *img, size_t img_size, int w, int h, int tlut_fmt, const uint8_t *tlut, int tlut_n)
{ (void) gx_fmt; (void) img; (void) img_size; (void) w; (void) h; (void) tlut_fmt; (void) tlut; (void) tlut_n; g_art_calls++; snprintf(g_art_key, sizeof g_art_key, "%s", key); return g_art_ret; }
int gw_Kit_QuadCount(void) { return g_quads; }
int gw_Kit_QuadRoom(void) { return 16000; }

#include "gw_script_ui.inc"

static const char *lua(const char *code)
{
    static char buf[512];
    lua_State *L = gs.L;
    int top = lua_gettop(L);
    buf[0] = '\0';
    if (luaL_dostring(L, code) != LUA_OK) snprintf(buf, sizeof buf, "ERR %s", lua_tostring(L, -1));
    else if (lua_gettop(L) > top) snprintf(buf, sizeof buf, "%s", luaL_tolstring(L, -1, NULL));
    lua_settop(L, top);
    snprintf(g_last, sizeof g_last, "%s", buf);
    return buf;
}
static int t_lua(const char *code) { return strncmp(lua(code), "ERR", 3) != 0; }
static const char *t_lua_err(void) { return g_last; }

static unsigned bswap_u(unsigned v) { return (v >> 24) | ((v >> 8) & 0xFF00u) | ((v << 8) & 0xFF0000u) | (v << 24); }
/* the adapter reads these out-parameters from game memory with byte-swapped loads: read them back the same way */
static int poll(int h, int *k, int *a, int *b)
{
    int r = gw_Ui_SelPoll(h, k, a, b);
    if (r) { *k = (int) bswap_u((unsigned) *k); *a = (int) bswap_u((unsigned) *a); *b = (int) bswap_u((unsigned) *b); }
    return r;
}
static void reset_ui(void)
{
    int i;
    for (i = 0; i < GS_UI_SLOTS; i++) { memset(&gs_ui_slot[i], 0, sizeof gs_ui_slot[i]); gs_ui_slot[i].dialog_fn = -1; }
    memset(&gs_ui_stack, 0, sizeof gs_ui_stack);
    gs_ui_qn = 0; g_pad = 0; gs.cur = 0; gs.scene_kind = 7;
    gs_sel.h = -1; gs_sel.qn = 0;
    g_mx = g_my = -1000.0f; g_mbuttons = 0; g_mwheel = 0.0f; g_art_calls = 0; g_images = 0;
    for (i = 1; i < 8; i++) gs.s[i].used = 0;
}
static void fake_script(int i, const char *mod) { snprintf(gs.s[i].id, sizeof gs.s[i].id, "%s/main", mod); gs.s[i].used = 1; gs.s[i].disabled = 0; }

/* the walker calls the shims unprefixed (the game's way); in this binary they are the host's own gw_ functions */
#define Ui_SetRows gw_Ui_SetRows
#define Ui_SetRow gw_Ui_SetRow
#define Ui_SetRowVal gw_Ui_SetRowVal
#define Ui_SetRowText gw_Ui_SetRowText
#define Ui_SetRowOpt gw_Ui_SetRowOpt
#define Ui_ItemStep gw_Ui_ItemStep
#include "../../src/melee/gm/gmfrontend_items.h"
#include "../../src/melee/gm/gmfrontend_atlas_table.h"
#include "atlas_style.h"

typedef struct { const char *name; const FrontendItem *rows; int n; const int *nopts; } StubTable;
static int g_gv = 7, g_gvis = 1, g_gen = 1, g_gsets, g_glast, g_gcalls;
static int gen_get(void) { return g_gv; }
static void gen_set(int v) { g_gv = v; g_gsets++; g_glast = v; }
static void gen_fmt(int v, char *out) { snprintf(out, FSS_TEXT, "value %d", v); }
static int gen_vis(void) { return g_gvis; }
static int gen_en(void) { return g_gen; }
static void gen_call(void) { g_gcalls++; }
#include "atlas_settings_tables.inc"

static const StubTable *tbl(const char *n)
{
    int i;
    for (i = 0; i < (int) (sizeof all_tables / sizeof all_tables[0]); i++) if (strcmp(all_tables[i].name, n) == 0) return &all_tables[i];
    return NULL;
}
static int ntables(void) { return (int) (sizeof all_tables / sizeof all_tables[0]); }
static GsUiSlot *slot_of(int h) { return &gs_ui_slot[h & 0xFF]; }
static void reset_set(void)
{
    reset_ui();
    gs_set.h = -1; gs_set.qn = 0; gs_set.frozen = 0; gs_set.answer = 0; gs_set.pending = 0; gs_set.fid[0] = '\0'; gs_set.fidx = -1;
    memset(gs.key_now, 0, sizeof gs.key_now);
    g_gv = 7; g_gvis = 1; g_gen = 1; g_gsets = 0; g_gcalls = 0;
}
static const char *focused_id(int h)
{
    int s = gw_Ui_SetFocused(h);
    return (s >= 0 && s < slot_of(h)->sc.n_items) ? slot_of(h)->sc.items[s].id : "";
}
/* open the settings screen and show one table through the real walker and the real shims */
static int show(const FrontendScreen *s, FssVis *v)
{
    int h = gw_Ui_SetOpen(0, 0, "MAIN MENU", "", "SETTINGS");
    if (h < 0) return h;
    gw_Ui_SetTabs(h, 6, "VIDEO,AUDIO,CONTROLS,ONLINE,GAME,MODS", 0);
    fss_visible(s, v); fss_table_submit(h, s, v);
    return h;
}
static void resubmit(int h, const FrontendScreen *s, FssVis *v) { fss_visible(s, v); fss_table_submit(h, s, v); }
static AtRect hit_row(const AtHits *hits, int i)
{
    int k;
    AtRect none = { 0, 0, 0, 0 };
    for (k = 0; k < hits->n; k++) if (hits->h[k].kind == AT_HIT_CELL && hits->h[k].b == i) return hits->h[k].r;
    return none;
}
/* every recorded text that sits on a row lies inside that row, measured with the width that drew it */
static int texts_in_rows(const AtHits *hits)
{
    int i, k;
    for (i = 0; i < REC.nt; i++) for (k = 0; k < hits->n; k++) {
        const AtRect *r;
        if (hits->h[k].kind != AT_HIT_CELL) continue;
        r = &hits->h[k].r;
        if (REC.t[i].base > r->y + 2.0f && REC.t[i].base < r->y + r->h && text_right(&REC.t[i]) > r->x && text_left(&REC.t[i]) < r->x + r->w)
            if (text_left(&REC.t[i]) < r->x - 0.01f || text_right(&REC.t[i]) > r->x + r->w + 0.01f) { printf("  text \"%s\" leaves its row\n", REC.t[i].s); return i; }
    }
    return -1;
}
static void render_screen(int h, float w, AtHits *hits)
{
    AtSink s = rec_sink();
    at_render(&slot_of(h)->sc, &slot_of(h)->view, w, 10000.0, 1, &FAKE, &s, hits);
}

static void page_counts(void)
{
    CHECK(ntables() == 9);
    CHECK(tbl("fe_items_set_video")->n == 6 && tbl("fe_items_set_audio")->n == 3 && tbl("fe_items_set_controls")->n == 12);
    CHECK(tbl("fe_items_set_online")->n == 6 && tbl("fe_items_set_gameplay")->n == 10 && tbl("fe_items_remap")->n == 20 && tbl("fe_items_howto_online")->n == 6);
    CHECK(tbl("fe_items_vs_setup")->n == 10 && tbl("fe_items_online")->n == 9);
}

/* per page, at 640 and 853, with every row enabled and then every enabled predicate failing: the style checks on every row kind the page contains */
static void every_row_is_drawable(void)
{
    static AtHits hits;
    int t, w, en, i;
    for (t = 0; t < ntables(); t++) for (w = 0; w < 2; w++) for (en = 0; en < 2; en++) {
        const StubTable *T = &all_tables[t];
        FrontendScreen scr; FssVis v; int h;
        AtRect canvas; float cw = w ? 853.3333f : 640.0f;
        canvas.x = 0.0f; canvas.y = 0.0f; canvas.w = cw; canvas.h = 480.0f;
        scr.title = "SETTINGS"; scr.subtitle = T->name; scr.items = T->rows; scr.n_items = T->n; scr.art = 0;
        reset_set(); g_gen = en;
        h = show(&scr, &v);
        CHECK(h >= 0 && v.n == T->n);
        for (i = 0; i < v.n; i++) {                                       /* each row in turn: drawn at rest, then focused with its three cues */
            AtRect row, area;
            StySig rest, foc;
            int other = i == 0 ? 1 : 0, scroll;
            slot_of(h)->view.focus.index = i; gs_ui_fix_scroll(slot_of(h)); scroll = slot_of(h)->view.scroll;   /* the window that holds row i */
            slot_of(h)->view.focus.index = other; slot_of(h)->view.scroll = scroll;                             /* the focus is elsewhere: row i is at rest */
            render_screen(h, cw, &hits);
            row = hit_row(&hits, i);
            CHECK(row.w > 0.0f);
            area.x = row.x - 4.0f; area.y = row.y - 4.0f; area.w = row.w + 8.0f; area.h = row.h + 8.0f;
            rest = sty_sig_in(0, area);
            CHECK(corners_clear(row, (float) AT_PX_CH_S));
            CHECK(texts_legible());
            CHECK(sty_text_inside(canvas, 0) == -1);                        /* nothing leaves the canvas */
            CHECK(texts_in_rows(&hits) == -1);                              /* nothing runs out of its row: a label, a value and a reason fit or are cut */
            slot_of(h)->view.focus.index = i; slot_of(h)->view.scroll = scroll;
            render_screen(h, cw, &hits);
            foc = sty_sig_in(0, area);
            CHECK(sty_focus_cues(rest, foc) == 3);                          /* lift, ember edge and tick on every kind the page has */
        }
        gw_Ui_SetClose(h);
    }
}

/* Review Focus 2: min, max, step and wrap per row, through the same rule the walker uses, with the real ranges */
static void round_trips(void)
{
    int t, i;
    for (t = 0; t < ntables(); t++) {
        const StubTable *T = &all_tables[t];
        FrontendScreen scr; FssVis v;
        scr.title = "T"; scr.subtitle = "S"; scr.items = T->rows; scr.n_items = T->n; scr.art = 0;
        g_gvis = 1; g_gen = 1;
        fss_visible(&scr, &v);
        CHECK(v.n == T->n);
        for (i = 0; i < T->n; i++) {
            const FrontendItem *it = &T->rows[i];
            unsigned fx;
            CHECK(it->help != NULL && it->help[0] != '\0');                  /* every row explains itself (the explainer's WHAT) */
            CHECK(it->label != NULL && it->label[0] != '\0');
            if (it->kind == FE_SLIDER && it->set != NULL) {
                CHECK(it->max > it->min);                                    /* a settable slider has a range */
                g_gv = it->max; g_gsets = 0; fx = fss_table_event(&scr, &v, i, FSS_EV_CHANGE, +1);
                CHECK(g_gsets == 0 && (fx & FSS_FX_BUMP));                   /* held at the top: nothing set, the kit's bump */
                g_gv = it->min; g_gsets = 0; fx = fss_table_event(&scr, &v, i, FSS_EV_CHANGE, +1);
                CHECK(g_gsets == 1 && g_glast > it->min && g_glast <= it->min + (it->step > 0 ? it->step : 1) && (fx & FSS_FX_MOVE));
                g_gv = it->min; g_gsets = 0; fx = fss_table_event(&scr, &v, i, FSS_EV_CHANGE, -1);
                CHECK(g_gsets == 0 && (fx & FSS_FX_BUMP));                   /* and at the bottom */
            }
            if (it->kind == FE_CHOICE) {
                int n = it->max - it->min + 1;
                CHECK(T->nopts[i] == 0 || T->nopts[i] == n);                 /* the option strings cover the range */
                g_gv = it->max; g_gsets = 0; fss_table_event(&scr, &v, i, FSS_EV_CHANGE, +1);
                CHECK(g_gsets == 1 && g_glast == it->min);                   /* a choice wraps at the top ... */
                g_gv = it->min; g_gsets = 0; fss_table_event(&scr, &v, i, FSS_EV_CHANGE, -1);
                CHECK(g_gsets == 1 && g_glast == it->max);                   /* ... and at the bottom */
            }
            if (it->kind == FE_TOGGLE) {
                g_gv = 0; fss_table_event(&scr, &v, i, FSS_EV_CHANGE, +1); CHECK(g_glast == 1);
                g_gv = 1; fss_table_event(&scr, &v, i, FSS_EV_CHANGE, -1); CHECK(g_glast == 0);
            }
        }
    }
}

static void options_the_host_shows(void)
{
    const StubTable *T = tbl("fe_items_set_video");
    FrontendScreen scr; FssVis v; int h;
    AtItem *it;
    scr.title = "T"; scr.subtitle = "S"; scr.items = T->rows; scr.n_items = T->n; scr.art = 0;
    reset_set(); g_gv = 1;
    h = show(&scr, &v);
    it = &slot_of(h)->sc.items[1];                                          /* Render Scale: six options */
    CHECK(it->vkind == AT_VAL_CHOICE && it->n_opts == 6 && strcmp(it->text, "1x") == 0 && strcmp(it->opt[5], "4x") == 0);
    g_gv = 0; resubmit(h, &scr, &v); CHECK(strcmp(slot_of(h)->sc.items[1].text, "Auto (window)") == 0);   /* the text follows the value, every frame */
    gw_Ui_SetClose(h);
    /* the remap page's Game Input has 22 options: more than the record holds, so the walker shows the text */
    T = tbl("fe_items_remap");
    scr.items = T->rows; scr.n_items = T->n;
    reset_set(); g_gv = 3;
    h = show(&scr, &v);
    it = &slot_of(h)->sc.items[2];
    CHECK(it->vkind == AT_VAL_CHOICE && it->n_opts == 0 && strcmp(it->text, "Y") == 0);                  /* option 3 of fcr_targets */
    g_gv = 21; resubmit(h, &scr, &v); CHECK(strcmp(slot_of(h)->sc.items[2].text, "Analog R") == 0);
    gw_Ui_SetClose(h);
}

static void disabled_rows_say_why(void)
{
    static AtHits hits;
    const StubTable *T = tbl("fe_items_remap");
    FrontendScreen scr; FssVis v; int h, i, why = 0;
    scr.title = "T"; scr.subtitle = "S"; scr.items = T->rows; scr.n_items = T->n; scr.art = 0;
    reset_set(); g_gen = 0;
    h = show(&scr, &v);
    for (i = 0; i < v.n; i++) {
        const AtItem *it = &slot_of(h)->sc.items[i];
        if (it->flags & AT_CELL_DISABLED) { why++; CHECK(strcmp(it->reason, "Connect a controller to this port first.") == 0); }
    }
    CHECK(why == 5);                                                         /* Bind Input, New, Rename, Delete Profile, Reset to Default */
    render_screen(h, 640.0f, &hits);
    CHECK(find_text("Connect a controller to this port first.") != NULL && texts_legible());   /* said in words, not only dimmed */
    gw_Ui_SetClose(h);
    reset_set(); g_gen = 1;
    h = show(&scr, &v);
    for (i = 0; i < v.n; i++) CHECK(!(slot_of(h)->sc.items[i].flags & AT_CELL_DISABLED));
    gw_Ui_SetClose(h);
}

/* Review Focus 5: the Stick Dead Zone row (fsc_any_sdl) shows and hides; focus follows by id */
static void visible_rows_change(void)
{
    const StubTable *T = tbl("fe_items_set_controls");
    FrontendScreen scr; FssVis v; int h;
    scr.title = "T"; scr.subtitle = "S"; scr.items = T->rows; scr.n_items = T->n; scr.art = 0;
    reset_set(); g_gvis = 1;
    h = show(&scr, &v);
    CHECK(slot_of(h)->sc.n_items == 12 && strcmp(slot_of(h)->sc.items[6].id, "i6") == 0 && strcmp(slot_of(h)->sc.items[6].label, "Stick Dead Zone") == 0);
    gw_Ui_SetFocus(h, "i6");
    g_gvis = 0; resubmit(h, &scr, &v);
    CHECK(slot_of(h)->sc.n_items == 11 && strcmp(focused_id(h), "i7") == 0);   /* the next visible row, never nothing */
    g_gvis = 1; resubmit(h, &scr, &v);
    CHECK(slot_of(h)->sc.n_items == 12 && strcmp(focused_id(h), "i7") == 0);   /* and when it comes back the focus stays where it is */
    gw_Ui_SetFocus(h, "i11"); g_gvis = 0; resubmit(h, &scr, &v);
    CHECK(strcmp(focused_id(h), "i11") == 0);                                  /* a row after the hidden one keeps its id */
    gw_Ui_SetClose(h);
}

static void mods_41_rows_and_help(void)                                  /* Review Focus 9 */
{
    static FrontendItem M[41];
    static char help[41][520];
    static AtHits hits;
    FrontendScreen scr; FssVis v; int h, i, seen = 0, found = 0;
    AtLayout L;
    memset(M, 0, sizeof M);
    M[0].kind = FE_SLIDER; M[0].label = "Mods"; M[0].help = "Turn mods on or off."; M[0].get = gen_get; M[0].format = gen_fmt;
    for (i = 1; i < 41; i++) {
        memset(help[i], 'x', 511); help[i][511] = '\0';                       /* a 511-character mod help line (FE_HELP_STR) */
        M[i].kind = FE_TOGGLE; M[i].label = "A Mod With A Name"; M[i].help = help[i]; M[i].get = gen_get; M[i].set = gen_set; M[i].max = 1; M[i].step = 1;
    }
    scr.title = "SETTINGS"; scr.subtitle = "MODS"; scr.items = M; scr.n_items = 41; scr.art = 0;
    reset_set();
    h = show(&scr, &v);
    CHECK(v.n == 41 && slot_of(h)->sc.n_items == 41);                         /* 41 rows fit the record */
    gw_Ui_SetFocus(h, "i40"); gw_Ui_SetExplain(h, NULL, NULL, NULL, NULL, "");
    CHECK(strlen(slot_of(h)->view.ex.what) <= AT_TEXT - 1 && strstr(slot_of(h)->view.ex.what, "...") != NULL);   /* help_clamped: an ellipsis, not an overflow */
    render_screen(h, 640.0f, &hits);
    at_layout(640.0f, AT_PRESET_NORMAL, &L);
    CHECK(texts_legible());
    for (i = 0; i < REC.nt; i++) if (strncmp(REC.t[i].s, "xxx", 3) == 0) {
        CHECK(text_left(&REC.t[i]) >= L.explainer.x - 0.01f && text_right(&REC.t[i]) <= L.explainer.x + L.explainer.w + 0.01f); seen++;
    }
    CHECK(seen >= 1 && seen <= 4);                                            /* wrapped to at most 4 lines, all inside the explainer */
    for (i = 0; i < hits.n; i++) if (hits.h[i].kind == AT_HIT_CELL && hits.h[i].b == 40) found = 1;
    CHECK(found);                                                             /* the 41st row is on screen when it has the focus */
    gw_Ui_SetClose(h);
}

static void explainer_from_the_row(void)
{
    const StubTable *T = tbl("fe_items_set_audio");
    FrontendScreen scr; FssVis v; int h;
    const AtExplainer *e;
    scr.title = "T"; scr.subtitle = "S"; scr.items = T->rows; scr.n_items = T->n; scr.art = 0;
    reset_set(); g_gv = 45;
    h = show(&scr, &v);
    gw_Ui_SetFocus(h, "i0"); gw_Ui_SetExplain(h, NULL, NULL, NULL, NULL, "");
    e = &slot_of(h)->view.ex;
    CHECK(strcmp(e->kicker, "VIDEO") == 0);                                   /* the tab strip says VIDEO here: the adapter names the tab, the test only the first */
    CHECK(strcmp(e->title, "Master Volume") == 0 && strcmp(e->what, "Everything the game plays.") == 0 && strcmp(e->now_text, "NOW value 45") == 0);   /* a slider's NOW is the game's own format */
    gw_Ui_SetFocus(h, "i2"); gw_Ui_SetExplain(h, NULL, NULL, NULL, NULL, "");
    CHECK(strcmp(e->title, "Output") == 0 && e->now_text[0] == '\0');         /* value 45 is outside the two options: nothing is claimed */
    g_gv = 1; resubmit(h, &scr, &v); gw_Ui_SetExplain(h, NULL, NULL, NULL, NULL, "");
    CHECK(strcmp(e->now_text, "NOW Mono") == 0);
    CHECK(e->no_well == 1 && e->media_model == AT_NO_MODEL);                  /* no media well: the controller diagram and the render sketch are not built */
    gw_Ui_SetClose(h);
}

int main(void)
{
    lua_State *L = luaL_newstate();
    gs.L = L; gs.cur = 0; gs.console = 0;
    snprintf(gs.s[0].id, sizeof gs.s[0].id, "console");
    snprintf(gs.s[1].id, sizeof gs.s[1].id, "envoy/main");
    gs.n = 8; gs.s[0].used = gs.s[1].used = gs.s[2].used = 1;
    luaL_openlibs(L);
    lua_newtable(L); gs_push_ui(L); lua_setfield(L, -2, "ui"); lua_setglobal(L, "gd");
    page_counts(); every_row_is_drawable(); round_trips(); options_the_host_shows(); disabled_rows_say_why(); visible_rows_change(); mods_41_rows_and_help(); explainer_from_the_row();
    lua_close(L);
    ATLAS_DONE("atlas settings pages");
}
