"""Bundle the sandbox-compatible campaign test; no compilation or game launch."""
from pathlib import Path

HERE = Path(__file__).resolve().parent
parts = [HERE.parent / 'scripts/lib/campaign_save.lua', HERE / 'campaign-save-body.lua']
header = '-- @name: campaign-save\n-- @gameplay: true\n-- @rollback_safe: false\n'
header += '-- Generated by pc/tests/bundle_campaign_save.py; edit library/body instead.\n'
(HERE / 'campaign-save.lua').write_text(
    header + '\n'.join(p.read_text(encoding='utf-8') for p in parts), encoding='utf-8', newline='\n')
