local T=dofile((io.open('pc/tests/envoy_testlib.lua') and '' or 'melee/')..'pc/tests/envoy_testlib.lua')
local D=T.rules();local V=T.module('drives',D)
T.test('seven kinds mostly their mapped colour',function()
  for kind,colour in pairs(V.kinds) do
    local v=V.new(function() return .1 end);v:track(1,{kind=kind,x=3,y=4})
    assert(v:defeat({handle=1,kind=kind},D.companion.new()));assert(v.pickups[1].colour==colour)
  end
end)
T.test('native defeat only, unknown and duplicate events ignored',function()
  local v=V.new(function() return .1 end);local c=D.companion.new()
  assert(not v:defeat({handle=5,kind='goomba'},c));v:track(5,{kind='goomba',x=0,y=0})
  assert(v:defeat({handle=5,kind='goomba'},c));assert(not v:defeat({handle=5,kind='goomba'},c))
  assert(#v.pickups==1)
end)
T.test('rare white and no drop branch deterministic',function()
  local v=V.new(function() return 0 end);v:track(1,{kind='topi',x=0,y=0})
  v:defeat({handle=1,kind='topi'},D.companion.new());assert(v.pickups[1].colour=='white')
  v=V.new(function() return .99 end);v:track(1,{kind='goomba',x=0,y=0})
  v:defeat({handle=1,kind='goomba'},D.companion.new());assert(#v.pickups==0)
end)
T.test('Jump leaves fixed touch collection and expiry counts logic frames',function()
  local v=V.new(function() return .1 end);local c=D.companion.new()
  v:track(1,{kind='goomba',x=22,y=0});v:defeat({handle=1,kind='goomba'},c)
  v:tick({x=0,y=0},c);assert(c.stats.power.points==0)
  D.companion.feed(c,'yellow',2000);assert(#v:tick({x=0,y=0},c)==0 and c.stats.power.points==0)
  local collected=v:tick({x=5,y=0},c);assert(c.stats.power.points>0 and #v.pickups==0)
  assert(#collected==1 and collected[1].colour=='red' and collected[1].grade=='C')
  v:track(2,{kind='koopa',x=100,y=0});v:defeat({handle=2,kind='koopa'},c)
  for _=1,D.companion.tuning.drive_lifetime do v:tick(nil,c) end;assert(#v.pickups==0)
  v:clear();assert(next(v.tracked)==nil)
end)
T.test('depth changes real native payload and fallback reward once',function()
 local c=D.companion.new();local native={};local v=V.new(function() return .1 end,nil,{item_spawn=function(_,_,_,o) native=o.payload;return 7 end})
 v:set_depth(3);v:track(1,{kind='goomba',x=0,y=0});v:defeat({handle=1,kind='goomba'},c)
 assert(native.amount==D.companion.tuning.depth_drive_points[3]);local at=c.stats.power.points
 assert(v:collect({name='drive',port=1,item=7,payload=native},c));assert(c.stats.power.points-at==native.amount)
 assert(not v:collect({name='drive',port=1,item=7,payload=native},c))
 local f=V.new(function() return .1 end);f:set_depth(4);f:track(2,{kind='goomba',x=0,y=0});f:defeat({handle=2,kind='goomba'},c)
 at=c.stats.power.points;f:tick({x=0,y=0},c);assert(c.stats.power.points-at==D.companion.tuning.depth_drive_points[4])
end)
T.test('fixed drop probability is identical for all depths and evolution types',function()
 for depth=1,4 do for _,kind in ipairs({'young','jump','balanced'}) do
  local c=D.companion.new();c.type=kind;D.companion.feed(c,'yellow',2000)
  local v=V.new(function() return .81 end);v:set_depth(depth);v:track(1,{kind='goomba',x=0,y=0})
  assert(v:defeat({handle=1,kind='goomba'},c) and #v.pickups==0)
 end end
end)
T.done()
