-- The run's fighter: the retail roster, a Geno fighter listed in fighters.txt, plain refusals, and nameplates for "character N".
local T=dofile('melee/pc/tests/envoy_testlib.lua')
local D={};D.fighters=T.module('fighters',D)
local F=D.fighters
local function g(text) return {mod_read=function(path) assert(path=='missions/fighters.txt');if text==nil then return nil,'missing' end return text end} end
T.test('the file lists Geno fighters; comments, junk and duplicates are ignored',function()
 local l=F.parse('# note\ngeno:vanilla-hero  Vanilla Hero\nnot a fighter\ngeno:vanilla-hero again\ngeno:Brawl_Kirby\n')
 assert(#l==2 and l[1].id=='geno:vanilla-hero' and l[1].label=='Vanilla Hero' and l[2].id=='geno:Brawl_Kirby' and l[2].label=='Brawl_Kirby')
 assert(#F.extras(g(nil))==0 and #F.extras({})==0)
end)
T.test('the menu offers the retail roster and, when listed, the Geno fighter',function()
 local plain=F.menu(g('# none\n'));assert(#plain==#F.retail and plain[1]=='fox')
 local m=F.menu(g('geno:vanilla-hero  Vanilla Hero\n'));assert(#m==#F.retail+1 and m[#m].id=='geno:vanilla-hero' and m[#m].label=='Vanilla Hero')
 local M=T.module('menu');local s=M.new();s:show('fighter');s.focus.fighter=#m
 local e=s:input('accept',{fighters=m});assert(e.type=='fighter' and e.fighter=='geno:vanilla-hero' and s.fighter=='geno:vanilla-hero')
 e=s:input('accept',{fighters=m});assert(e.type=='start' and e.fighter=='geno:vanilla-hero')
end)
T.test('a command token is resolved or refused plainly',function()
 local gg=g('geno:vanilla-hero  Vanilla Hero\n')
 assert(F.resolve(gg,'Marth')=='marth' and F.resolve(gg,'geno:vanilla-hero')=='geno:vanilla-hero')
 local id,why=F.resolve(gg,'sonic');assert(id==nil and why:find("unknown fighter 'sonic'",1,true) and why:find('fox',1,true))
 id,why=F.resolve(g(nil),'geno:vanilla-hero');assert(id==nil and why:find('not mounted',1,true))
 id,why=F.resolve(gg,'');assert(id==nil and why)
end)
T.test('a nameplate never reads "character 127"',function()
 local one=g('geno:vanilla-hero  Vanilla Hero\n')
 assert(F.plate(one,'Fox')=='Fox' and F.plate(one,'character 127')=='Vanilla Hero' and F.plate(one,nil)=='Vanilla Hero')
 assert(F.plate(g('geno:a A\ngeno:b B\n'),'character 9')=='Custom fighter' and F.plate(g(nil),'character 127','Hero token')=='Hero token')
end)
T.done()
