local T=dofile('melee/pc/tests/envoy_testlib.lua');local D={}
for _,name in ipairs{'mod_schema','mod_codec','mod_engine','mod_pool'} do D[name]=T.module(name,D) end
T.test('native conversion records compile in fixed order and do not name moves',function()
 local r=D.mod_engine.new(5,D.mod_pool);r:equip(1,'burning');r:equip(1,'charged');r:equip(1,'pyre')
 local rules,bits=r:native_rules(1);assert(bits==0 and #rules==3)
 assert(rules[1].match.move=='smash' and rules[1].change.element=='fire')
 assert(rules[2].match.move=='aerial' and rules[2].change.element=='electric')
 assert(rules[3].match.status_bits==1 and rules[3].change.knockback_taken==1.25)
 local m=D.mod_codec.decode(D.mod_codec.encode(r.rules.burning));m.effects[1].match.move='MarioAttackS4'
 T.refuses(function()D.mod_schema.validate(m)end)
 m.effects[1].match.move='smash';m.effects[1].change.element='sleep';T.refuses(function()D.mod_schema.validate(m)end)
 m.effects[1].change.element='fire';m.effects[1].change.fraction=.5;T.refuses(function()D.mod_schema.validate(m)end)
end)
T.test('native versus-status uses the actual mask and trace IDs',function()
 local r=D.mod_engine.new(7,D.mod_pool);r:equip(1,'pyre');r.statuses[2]={burn={stacks=1,max=1,expires=180,next_tick=60,amount=3,origin={}}}
 local rules=r:native_rules(1);local none,bits=r:native_rules(2);assert(#none==0 and bits==1)
 local origin=r:native_origin({rules[1].id});assert(origin[1]:match('by Pyre$'))
 r:begin_frame({[1]={percent=30},[2]={percent=0}})
 r:emit{kind='hit_dealt',port=1,target=2,tags={normal=true},origin=origin,native_trace=true};r:drain()
 assert(not r:status(2,'curse') and r.trace[1]:match('Pyre'))
end)
T.test('Pyromancer is a real equip conversion with an explicit defensive cost',function()
 local r=D.mod_engine.new(1,D.mod_pool);r:equip(1,'pyromancer')
 local rules=r:native_rules(1);assert(#rules==2 and rules[1].match.move=='any' and rules[1].change.element=='fire')
 assert(rules[2].match.incoming and rules[2].match.element=='ice' and rules[2].change.damage==2 and r.rules.pyromancer.kind=='keystone')
 local snap=r:export();r:clear();assert(#r:native_rules(1)==0);r:import(snap);assert(r:export()==snap)
 T.refuses(function()r:equip(1,'still_heart')end)
end)
T.done()
