local T=dofile('melee/pc/tests/envoy_testlib.lua');local D=T.rules()
D.mod_echo=T.module('mod_echo',D);D.mod_schema=T.module('mod_schema',D);D.mod_codec=T.module('mod_codec',D);D.mod_pool=T.module('mod_pool',D);D.mod_engine=T.module('mod_engine',D)
T.test('aerial copy tiers and bounded depth cost',function()
 local e=D.mod_engine.new(1,D.mod_pool)
 for tier=1,3 do e:set_build(1,{echoes=tier},{});local d=e:echo_description(1);assert(#d.copies==tier)
 for i,c in ipairs(d.copies)do assert(c.age==i*8 and c.echo.damage==.4 and c.echo.match.move=='aerial' and c.echo.once_per_move)end end
 e:set_build(1,{echoes=100},{});assert(#e:echo_description(1).copies==3);local _,s=e:family_budget(1);assert(s>1)
end)
T.test('owner neutral air and status presentation',function()
 local d=D.mod_echo.description{copies=3,slots={1,2},delay=8,match={move='nair'},damage=.4,knockback=1,once_per_move=true}
 assert(d.copies[1].echo and d.copies[2].echo and not d.copies[3].echo)
 local e=D.mod_engine.new(1,D.mod_pool);e:set_build(1,{trailing=1},{})
 assert(#e:echo_description(1).copies==0);e.statuses[1]={haste={}};d=e:echo_description(1);assert(#d.copies==3 and not d.copies[1].echo)
 T.refuses(function()D.mod_echo.description{copies=3,slots={4},delay=8,damage=.4}end)
end)
T.test('all move costs and checkpoint determinism',function()
 local e=D.mod_engine.new(1,D.mod_pool);e:set_build(1,{echo_heart=1},{})
 assert(e:values(1).damage_dealt==.75 and e:echo_description(1).copies[1].echo.match.move=='any')
 local r=D.mod_engine.new(1,D.mod_pool);r:import(e:export());assert(r:export()==e:export())
end)
T.test('same-age different filters retain independent rules and shared strength',function()
 local e=D.mod_engine.new(1,D.mod_pool);e:set_build(1,{echoes=3,echo_heart=1},{})
 local d=e:echo_description(1);assert(#d.copies==3 and #d.rules==6)
 local aerial,any=0,0;for _,r in ipairs(d.rules)do assert(r.damage==.4);if r.match.move=='aerial' then aerial=aerial+1 else any=any+1 end end
 assert(aerial==3 and any==3);local budget=e:family_budget(1);assert(math.abs(budget.echo.potential-3.4)<1e-9)
end)
T.test('the echo description is kept under the build and the statuses echo rules read, not every status',function()
 local e=D.mod_engine.new(1,D.mod_pool);e:set_build(1,{trailing=1},{});e.statuses[1]={haste={stacks=1,amount=1,expires=9}}
 local a=e:echo_description(1);assert(#a.copies==3)
 e.statuses[1].guarded={stacks=1,amount=1,expires=9};assert(e:echo_description(1)==a,'a status no echo reads redescribed the echo')
 e.statuses[1].haste=nil;assert(#e:echo_description(1).copies==0,'the status echo rules wait for still counts')
 e.statuses[1].haste={stacks=1,amount=1,expires=9};assert(#e:echo_description(1).copies==3)
 e:set_build(1,{trailing=1,echoes=1},{});assert(e:echo_description(1)~=a,'a build change redescribes')
end)
T.done()
