local T=dofile((io.open('pc/tests/envoy_testlib.lua') and '' or 'melee/')..'pc/tests/envoy_testlib.lua')
local D=T.rules();local S=T.module('save',D)
local function settle(p,reason,frames)
  S.record_result(p,reason,frames)
  p.last_settled=p.next_run;p.next_run=p.next_run+1;p.last_result=reason
end
T.test('records count settled runs and only winning logic frames',function()
  local p=S.new_profile();settle(p,'win',120);settle(p,'fail',10);settle(p,'quit',5);settle(p,'win',180);settle(p,'win',60)
  p=S.decode(S.encode(p));assert(p.last_settled==5 and p.records.wins==3 and p.records.best_frames==60 and p.records.unknown_runs==0)
end)
T.test('legacy migration retains known run count without inventing wins or times',function()
  local p=S.new_profile();p.last_settled=7;p.next_run=8;p.last_result='win';p.records.runs=7
  local legacy=S.encode(p):gsub('ENVOY 4','ENVOY 1'):gsub('dna jump ','dna reach '):gsub('stat jump ','stat reach '):gsub('records [^\n]+\n',''):gsub('seeds [^\n]+\n',''):gsub('life [^\n]+\n',''):gsub('(stat %w+ %w+ %d+ %d+) %w+ %d+ %d+','%1')
  local writes=0;local store=S.open({data_read=function() return legacy end,data_write_atomic=function() writes=writes+1;return true end})
  assert(store.profile and writes==0);p=store.profile
  assert(p.last_settled==7 and p.records.unknown_runs==7 and p.records.wins==0 and p.records.best_frames==0)
  settle(p,'win',240);assert(store:commit(p));assert(writes==1 and store.profile.records.wins==1 and store.profile.records.unknown_runs==7)
end)
T.test('failed replacement preserves records; retry writes same prepared settlement',function()
  local old=S.encode(S.new_profile());local bytes=old;local fail=true;local writes=0
  local store=S.open({data_read=function() return bytes end,data_write_atomic=function(_,text) writes=writes+1;if fail then return false,'full' end;bytes=text;return true end})
  local pending=S.decode(old);settle(pending,'win',360)
  assert(not store:commit(pending));assert(bytes==old and store.profile.records.wins==0)
  fail=false;assert(store:commit(pending));assert(writes==2 and store.profile.last_settled==1 and store.profile.records.wins==1)
end)
T.test('invalid and truncated records refuse; future schema remains refused',function()
  local p=S.new_profile();p.records.wins=1;T.refuses(function() S.encode(p) end)
  p=S.new_profile();p.records.best_frames=1;T.refuses(function() S.encode(p) end)
  p=S.new_profile();p.last_settled=1;p.next_run=2;p.last_result='win';p.records.wins=1;T.refuses(function() S.encode(p) end)
  T.refuses(function() S.record_result(S.new_profile(),'win',0) end)
  p=S.new_profile();p.records.unknown_runs=1;T.refuses(function() S.encode(p) end)
  T.refuses(function() S.decode(S.encode(S.new_profile()):gsub('records 0 0 0 0 0 3','records 0 0')) end)
  T.refuses(function() S.decode(S.encode(S.new_profile()):gsub('ENVOY 4','ENVOY 99')) end)
end)
T.test('first adult and completed lives count companions raised without duplication',function()
 local p=S.new_profile();local c=p.companions[1];D.companion.feed(c,'red',20);D.companion.evolve(c)
 S.refresh_records(p);S.refresh_records(p);assert(p.records.companions_raised==1)
 c.age=D.companion.tuning.lifespan;D.companion.reincarnate(c);S.refresh_records(p);assert(p.records.companions_raised==1)
 D.companion.start_run(c);D.companion.feed(c,'green',20);D.companion.evolve(c);S.refresh_records(p);assert(p.records.companions_raised==2)
end)
T.done()
