"""Bundle the library and demo into one sandbox entry; no game or asset build.

python pc/scripts/examples/gamemode_demo/bundle.py [--check]
Optional --output DIR --kit-models DIR prepares a mod with existing exported kit assets.
"""
import argparse
import json
from pathlib import Path
import shutil

HERE = Path(__file__).resolve().parent
LIB = HERE.parent.parent / "lib" / "gamemode.lua"
PARTS = ("bf_floor_4m", "bf_wall_solid_4m", "bf_wall_window_4m", "bf_wall_doorway_4m")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=HERE)
    parser.add_argument("--kit-models", type=Path)
    parser.add_argument("--source", type=Path, default=HERE / "demo.lua",
                        help="alternative source tail, e.g. tests/gamemode_boss_lane.lua")
    parser.add_argument("--test", type=Path,
                        help="append an integration test in the same sandbox/chunk as the demo")
    args = parser.parse_args()
    text = "-- Generated by gamemode_demo/bundle.py; edit lib/gamemode.lua and demo.lua.\n"
    text += LIB.read_text(encoding="utf-8") + "\n" + args.source.read_text(encoding="utf-8")
    if args.test:
        text += "\n" + args.test.read_text(encoding="utf-8")
    entry = args.output / "scripts" / "main.lua"
    if args.check:
        if not entry.is_file() or entry.read_text(encoding="utf-8") != text:
            raise SystemExit("gamemode bundle is stale")
        print("gamemode bundle: current")
        return
    # Verify the entire asset set before copying anything; source art is generated elsewhere.
    files = []
    if args.kit_models:
        for part in PARTS:
            files.extend([args.kit_models / (part + ext) for ext in (".gxmesh", ".coll.json")])
            sidecar = json.loads((args.kit_models / (part + ".coll.json")).read_text())
            atlas = sidecar["atlas"]
            files.append(args.kit_models / (atlas + ".gxtex"))
            glow = args.kit_models / (atlas + ".glow.gxtex")
            if glow.exists():
                files.append(glow)
        for path in files:
            if not path.is_file():
                raise SystemExit(f"missing exported kit asset: {path}")
    entry.parent.mkdir(parents=True, exist_ok=True)
    entry.write_text(text, encoding="utf-8", newline="\n")
    if args.output.resolve() != HERE:
        shutil.copy2(HERE / "mod.json", args.output / "mod.json")
    if files:
        dest = args.output / "models"
        dest.mkdir(exist_ok=True)
        for path in sorted(set(files)):
            shutil.copy2(path, dest / path.name)
    print(f"gamemode bundle: {entry}")


if __name__ == "__main__":
    main()
