"""Bundle lib/gamemode.lua + tail.lua into scripts/main.lua (no game, no asset build).

python pc/scripts/examples/boss_gamemode_bonus/bundle.py [--output DIR --kit-models DIR] [--one-hp] [--test FILE]
--one-hp: play bundle, Master Hand starts at 1 HP.  --test: append a same-chunk integration test.
"""
import argparse
import json
import shutil
from pathlib import Path

HERE = Path(__file__).resolve().parent
LIB = HERE.parent.parent / "lib" / "gamemode.lua"
PARTS = ("bf_floor_4m", "bf_wall_solid_4m", "bf_wall_window_4m", "bf_wall_doorway_4m")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--output", type=Path, default=HERE)
    ap.add_argument("--kit-models", type=Path)
    ap.add_argument("--one-hp", action="store_true")
    ap.add_argument("--test", type=Path)
    a = ap.parse_args()
    text = "-- Generated by boss_gamemode_bonus/bundle.py; edit lib/gamemode.lua and tail.lua.\n"
    if a.one_hp:
        text += "BOSSBONUS_ONE_HP = true\n"
    text += LIB.read_text(encoding="utf-8") + "\n" + (HERE / "tail.lua").read_text(encoding="utf-8")
    if a.test:
        text += "\n" + a.test.read_text(encoding="utf-8")
    files = []
    if a.kit_models:
        for part in PARTS:
            files += [a.kit_models / (part + e) for e in (".gxmesh", ".coll.json")]
            atlas = json.loads((a.kit_models / (part + ".coll.json")).read_text())["atlas"]
            files.append(a.kit_models / (atlas + ".gxtex"))
            glow = a.kit_models / (atlas + ".glow.gxtex")
            if glow.exists():
                files.append(glow)
        for f in files:
            if not f.is_file():
                raise SystemExit(f"missing exported kit asset: {f}")
    entry = a.output / "scripts" / "main.lua"
    entry.parent.mkdir(parents=True, exist_ok=True)
    entry.write_text(text, encoding="utf-8", newline="\n")
    if a.output.resolve() != HERE:
        shutil.copy2(HERE / "mod.json", a.output / "mod.json")
    if files:
        (a.output / "models").mkdir(exist_ok=True)
        for f in sorted(set(files)):
            shutil.copy2(f, a.output / "models" / f.name)
    print(f"boss_gamemode_bonus bundle: {entry}")


main()
