#!/usr/bin/env python3
"""Embed the example scripts into the exe as built-ins (pc/platform/gw_script_builtins.inc).

    python pc/scripts/gen_builtins.py

Every pc/scripts/examples/<name>.lua and pc/scripts/examples/<name>/ (mod.json + its entry) becomes
"builtin:<name>", loadable with the console's `load builtin:<name>` or MELEE_SCRIPT=builtin:<name>
without any file next to the exe. Rerun after editing an example and commit the .inc with it
(the build does not run Python).
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
EX = os.path.join(HERE, "examples")
OUT = os.path.join(HERE, "..", "platform", "gw_script_builtins.inc")


def c_string(text):
    out = []
    for line in text.replace("\r\n", "\n").split("\n"):
        esc = line.replace("\\", "\\\\").replace('"', '\\"')
        out.append('"%s\\n"' % esc)
    return "\n    ".join(out)


def main():
    entries = []
    for name in sorted(os.listdir(EX)):
        path = os.path.join(EX, name)
        if name.endswith(".lua"):
            entries.append((name[:-4], None, open(path, encoding="utf-8").read()))
        elif os.path.isdir(path) and os.path.isfile(os.path.join(path, "mod.json")):
            manifest = open(os.path.join(path, "mod.json"), encoding="utf-8").read()
            entry = json.loads(manifest).get("entry", "main.lua")
            entries.append((name, manifest, open(os.path.join(path, entry), encoding="utf-8").read()))
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* GENERATED by pc/scripts/gen_builtins.py from pc/scripts/examples - do not edit. */\n")
        for name, manifest, src in entries:
            f.write('{"%s",\n    %s,\n    %s},\n' % (name, c_string(manifest) if manifest else "NULL", c_string(src)))
    print("wrote %d built-in scripts to %s" % (len(entries), os.path.normpath(OUT)))


if __name__ == "__main__":
    main()
