#!/usr/bin/env python3
"""Generate pc/platform/gw_motion_names.inc: motion-state (action-state) names for the Geno Lab.

    python pc/geno/tools/gen_motion_names.py

The names are the decomp's own enums: ftCo_MS_* (ft/kinds/ftCommon/forward.h, the 341 common
states) and each vanilla fighter's <prefix>_MS_* enum that starts at ftCo_MS_Count (its special
states). A clone with no enum of its own takes its original's (Falco -> Fox, ...). m-ex fighters
get no table; gw_script.c names their special states from the animation symbol instead.
Rerun after the enums change and commit the .inc with it (the build does not run Python).
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", "..", ".."))
KINDS = os.path.join(ROOT, "src", "melee", "ft", "kinds")
OUT = os.path.join(ROOT, "pc", "platform", "gw_motion_names.inc")

# FighterKind order (ft/forward.h) -> kinds/ folder, then the fallback for a clone
FIGHTERS = [
    ("Mario", "ftMario", None), ("Fox", "ftFox", None), ("Captain", "ftCaptain", None),
    ("Donkey", "ftDonkey", None), ("Kirby", "ftKirby", None), ("Koopa", "ftKoopa", None),
    ("Link", "ftLink", None), ("Seak", "ftSeak", None), ("Ness", "ftNess", None),
    ("Peach", "ftPeach", None), ("Popo", "ftPopo", None), ("Nana", "ftNana", "ftPopo"),
    ("Pikachu", "ftPikachu", None), ("Samus", "ftSamus", None), ("Yoshi", "ftYoshi", None),
    ("Purin", "ftPurin", None), ("Mewtwo", "ftMewtwo", None), ("Luigi", "ftLuigi", None),
    ("Mars", "ftMars", None), ("Zelda", "ftZelda", None), ("CLink", "ftCLink", "ftLink"),
    ("DrMario", "ftDrMario", "ftMario"), ("Falco", "ftFalco", "ftFox"),
    ("Pichu", "ftPichu", "ftPikachu"), ("GameWatch", "ftGameWatch", None),
    ("Ganon", "ftGanon", "ftCaptain"), ("Emblem", "ftEmblem", "ftMars"),
    ("MasterH", "ftMasterHand", None), ("CrezyH", "ftCrazyHand", "ftMasterHand"),
    ("Boy", "ftZakoBoy", None), ("Girl", "ftZakoGirl", "ftZakoBoy"),
    ("GKoops", "ftGigaKoopa", "ftKoopa"), ("Sandbag", "ftSandbag", None),
]


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//[^\n]*", "", text)


def parse_enum(body, base_names):
    """Enumerators of one enum body -> {value: name}; `base_names` resolves ftCo_MS_Count."""
    values = {}
    known = dict(base_names)
    cur = -1
    for item in body.split(","):
        item = item.strip()
        if not item or item.startswith("#"):
            continue
        m = re.match(r"^(\w+)\s*(?:=\s*(.+))?$", item, flags=re.S)
        if not m:
            continue
        name, expr = m.group(1), m.group(2)
        if expr is not None:
            expr = expr.strip()
            e = re.match(r"^(\w+)\s*([+-])\s*(\w+)$", expr)
            if re.match(r"^-?(0x[0-9a-fA-F]+|\d+)$", expr):
                cur = int(expr, 0)
            elif expr in known:
                cur = known[expr]
            elif e and e.group(1) in known:
                rhs = e.group(3)
                n = known[rhs] if rhs in known else int(rhs, 0)
                cur = known[e.group(1)] + (n if e.group(2) == "+" else -n)
            else:
                sys.exit("cannot evaluate %s = %s" % (name, expr))
        else:
            cur += 1
        known[name] = cur
        if not name.endswith("_Count"):  # the Count / SelfCount markers name no state
            values.setdefault(cur, name)
    return values, known


def find_enums(path):
    text = strip_comments(open(path, encoding="utf-8").read())
    return re.findall(r"typedef\s+enum\s+\w*\s*\{(.*?)\}\s*\w+\s*;", text, flags=re.S)


def main():
    common_body = None
    for body in find_enums(os.path.join(KINDS, "ftCommon", "forward.h")):
        if "ftCo_MS_DeadDown" in body:
            common_body = body
    common, known = parse_enum(common_body, {})
    count = known["ftCo_MS_Count"]
    common_names = [common.get(i, "") for i in range(count)]

    def special(folder):
        path = os.path.join(KINDS, folder, "forward.h")
        if not os.path.isfile(path):
            return None
        for body in find_enums(path):
            if "= ftCo_MS_Count" in body.replace("\n", " "):
                vals, _ = parse_enum(body, {"ftCo_MS_Count": count})
                top = max(vals)
                return [vals.get(i, "") for i in range(count, top + 1)]
        return None

    def short(name):
        return re.sub(r"^\w+?_MS_", "", name)

    out = ["/* GENERATED by pc/geno/tools/gen_motion_names.py from the decomp's motion-state enums -",
           " * do not edit. Common states 0-%d, then each vanilla fighter's special states from %d. */" %
           (count - 1, count),
           "#define GW_MOTION_COMMON_COUNT %d" % count,
           "static const char *const gw_motion_common[%d] = {" % count]
    out += ['    "%s",' % short(n) for n in common_names]
    out.append("};")
    rows = []
    for kind, (label, folder, fallback) in enumerate(FIGHTERS):
        names = special(folder)
        src = folder
        if names is None and fallback is not None:
            names, src = special(fallback), fallback
        if not names:
            rows.append("    {NULL, 0}, /* %02X %s */" % (kind, label))
            continue
        var = "gw_motion_k%02X" % kind
        out.append("static const char *const %s[%d] = { /* %s (%s) */" % (var, len(names), label, src))
        out += ['    "%s",' % short(n) for n in names]
        out.append("};")
        rows.append("    {%s, %d}, /* %02X %s */" % (var, len(names), kind, label))
    out.append("static const struct {")
    out.append("    const char *const *names;")
    out.append("    int count;")
    out.append("} gw_motion_special[%d] = {" % len(FIGHTERS))
    out += rows
    out.append("};")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print("wrote %s (%d common, %d fighter tables)" % (OUT, count,
                                                       sum(1 for r in rows if "NULL" not in r)))


if __name__ == "__main__":
    main()
