/* Scalar fields returned by ScriptGame_ItemI/F across the PPC/native boundary. */
#ifndef PC_SCRIPT_ITEMS_H
#define PC_SCRIPT_ITEMS_H
enum { SCRIPT_ITEM_KIND, SCRIPT_ITEM_ID, SCRIPT_ITEM_OWNER, SCRIPT_ITEM_STATE,
       SCRIPT_ITEM_GENO_PROFILE, SCRIPT_ITEM_GENO_ARTICLE, SCRIPT_ITEM_GENO_FRAME };
enum { SCRIPT_ITEM_X, SCRIPT_ITEM_Y, SCRIPT_ITEM_Z, SCRIPT_ITEM_VX,
       SCRIPT_ITEM_VY, SCRIPT_ITEM_FACING };
#endif
